type User {
  netlifyID: ID!
  stripeID: ID!
  email: String!
}

type Query {
  getUserByNetlifyID(netlifyID: ID!): User!
  getUserByStripeID(stripeID: ID!): User!
  getUserByEmail(email: String!): User!
  allUser: [User!]
}